// <auto-generated />
namespace LoginSignup_in_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class catagories_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catagories_data));
        
        string IMigrationMetadata.Id
        {
            get { return "202309090620051_catagories_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
