// <auto-generated />
namespace Product_CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cattoproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cattoproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202308280648590_cat-to-product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
